[package]
name = "tantivy-py"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["dylib"]

[dependencies]
chrono = "0.4"
#tantivy = { git = "https://github.com/tantivy-search/tantivy" }
tantivy = {path="/home/paul/git/tantivy"}

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]
